In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [51]:
(x_train, y_train),(x,y_test) = keras.datasets.imdb.load_data(num_words=10000)
# Retrieve the word index file mapping words to indices
word_index = keras.datasets.imdb.get_word_index()
# Reverse the word index to obtain a dict mapping indices to words
inverted_word_index = dict((i, word) for (word, i) in word_index.items())
# Decode the first sequence in the dataset
decoded_sequence = " ".join(inverted_word_index[i] for i in x_train[0])

In [52]:
def decode_text(text):
    return " ".join(inverted_word_index[i] for i in text)
decode_text(x_train[2])

"the as there in at by br of sure many br of proving no only women was than doesn't as you never of hat night that with ignored they bad out superman plays of how star so stories film comes defense date of wide they don't do that had with of hollywood br of my seeing fan this of pop out body shots in having because cause it's stick passing first were enjoys for from look seven sense from me and die in character as cuban issues but is you that isn't one song just is him less are strongly not are you that different just even by this of you there is eight when it part are film's love film's 80's was big also light don't and as it in character looked cinematography so stories is far br man acting"

In [53]:
inverted_word_index[0] = "None"
x_test = keras.preprocessing.sequence.pad_sequences(x_test,value=0,maxlen=230,padding="post")
x_train = keras.preprocessing.sequence.pad_sequences(x_train,value=0,maxlen=230,padding="post")

In [54]:
model = keras.Sequential()
model.add(keras.layers.Embedding(25000,16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16,activation = 'relu'))
model.add(keras.layers.Dense(1,activation = "sigmoid"))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 16)          400000    
_________________________________________________________________
global_average_pooling1d_1 ( (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 400,289
Trainable params: 400,289
Non-trainable params: 0
_________________________________________________________________


In [55]:
model.compile(optimizer ='adam', loss='binary_crossentropy',metrics=['accuracy'])
x_val = x_train[:10000]
x_train = x_train[10000:]
y_val = y_train[:10000]
y_train = y_train[10000:]

In [58]:
model.fit(x_train,y_train,epochs =2,batch_size=1,validation_data=(x_val,y_val),verbose=1)
model.evaluate(x_test,y_test)

Epoch 1/5
15000/15000 [==============================] - 98s 7ms/step - loss: 0.1532 - accuracy: 0.9417 - val_loss: 0.3342 - val_accuracy: 0.8788
Epoch 2/5
15000/15000 [==============================] - 98s 7ms/step - loss: 0.1184 - accuracy: 0.9577 - val_loss: 0.3628 - val_accuracy: 0.8732
Epoch 3/5
15000/15000 [==============================] - 100s 7ms/step - loss: 0.0996 - accuracy: 0.9657 - val_loss: 0.4374 - val_accuracy: 0.8641
Epoch 4/5
15000/15000 [==============================] - 101s 7ms/step - loss: 0.0832 - accuracy: 0.9711 - val_loss: 0.4501 - val_accuracy: 0.8656
Epoch 5/5
782/782 [==============================] - 1s 805us/step - loss: 0.5611 - accuracy: 0.8440


[0.5611371994018555, 0.8440399765968323]

In [105]:
review = "it was a great movies i like to see it again"
predict = model.predict(x_test[:1])
predict

array([[0.19668913]], dtype=float32)

In [154]:
word_index
#review = "horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad horrible bad  horrible bad horrible bad horrible bad "
review = "this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie this is a really bad movie i won't see it again the main actor is horrible this is a really bad movie i won't see it again the main actor is horrible this is a really bad movie i won't see it again the main actor is horrible this is a really bad movie i won't see it again the main actor is horrible"
review = review.replace("bad","horrible")
new_review = [word_index[i] for i in str(review).lower().split()]
new_review = keras.preprocessing.sequence.pad_sequences([new_review],value=0,maxlen=230,padding="post")
model.predict([new_review])

array([[0.00082141]], dtype=float32)

In [153]:
new_review

array([[ 11,   6,   3,  63,  75,  17,  11,   6,   3,  63,  75,  17,  11,
          6,   3,  63,  75,  17,  11,   6,   3,  63,  75,  17,  11,   6,
          3,  63,  75,  17,  11,   6,   3,  63,  75,  17,  11,   6,   3,
         63,  75,  17,  11,   6,   3,  63,  75,  17,  11,   6,   3,  63,
         75,  17,  11,   6,   3,  63,  75,  17,  11,   6,   3,  63,  75,
         17,  11,   6,   3,  63,  75,  17,  11,   6,   3,  63,  75,  17,
         11,   6,   3,  63,  75,  17,  11,   6,   3,  63,  75,  17,  11,
          6,   3,  63,  75,  17,  11,   6,   3,  63,  75,  17,  11,   6,
          3,  63,  75,  17,  11,   6,   3,  63,  75,  17,  11,   6,   3,
         63,  75,  17,  11,   6,   3,  63,  75,  17,  11,   6,   3,  63,
         75,  17,  10, 525,  64,   9, 171,   1, 290, 281,   6, 524,  11,
          6,   3,  63,  75,  17,  10, 525,  64,   9, 171,   1, 290, 281,
          6, 524,  11,   6,   3,  63,  75,  17,  10, 525,  64,   9, 171,
          1, 290, 281,   6, 524,  11,   6,   3,  63

230

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)