In [2]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([[[1,2,3],
               [4,5,6]],
               [[7,8,9],
               [10,11,12]]
              ])
a.shape

(2, 2, 3)

In [12]:
a =a.reshape(1,6,2)

In [15]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
np.random.randint(1,10,size=(5,3))

array([[1, 5, 4],
       [3, 9, 6],
       [1, 1, 1],
       [1, 8, 9],
       [2, 2, 3]])

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [31]:
np.random.rand(5,3)

array([[0.2173202 , 0.84186301, 0.14369858],
       [0.95099544, 0.30310697, 0.32387745],
       [0.30766412, 0.37840177, 0.24199842],
       [0.64207565, 0.26595531, 0.77226389],
       [0.35255475, 0.96708874, 0.05963252]])

In [32]:
matrix = np.arange(1,10)
matrix = matrix.reshape(1,3,3)
matrix
#matrix = matrix.reshape(2,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [35]:
matrix.T

array([[[1],
        [4],
        [7]],

       [[2],
        [5],
        [8]],

       [[3],
        [6],
        [9]]])

In [34]:
matrix.reshape(3,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [15]:
matrix[1,2,2]

7

In [16]:
matrix.reshape(3,2,3)
matrix

array([[[3, 7, 9],
        [3, 0, 0],
        [8, 8, 4]],

       [[7, 3, 9],
        [2, 5, 2],
        [4, 7, 7]]])